  name: frontend-build

  on:
    pull_request:
      types:
        - open
      branches:
        - main
    workflow_dispatch:

  jobs:
    compile:
      runs-on: ubuntu-latest
      name: Compile project
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'liberica'

        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-${{ runner.os }}-

        - name: Build project
          run: |
            chmod +x ./mvnw
            ./mvnw clean compile

    build:
      runs-on: ubuntu-latest
      name: Build frontend
      needs: [compile]
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'liberica'

        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-${{ runner.os }}-

        - name: Build project
          run: |
            chmod +x ./mvnw
            ./mvnw clean package

    build-image:
      name: Build Docker image
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Get short git SHA code
          id: sha
          run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/lukeria-frontend:${{ steps.sha.outputs.SHA }}

    cleanup-images:
      name: Cleanup old Docker images
      runs-on: ubuntu-latest
      needs: [ build-image ]
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Install Docker CLI and jq
          run: |
            sudo apt-get update
            sudo apt-get install -y docker.io jq

        - name: Fetch and delete old Docker tags
          env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          run: |
            # Define the repository name
            REPO="$DOCKERHUB_USERNAME/lukeria-frontend"

            # Fetch all tags for the repository using Docker Hub API
            TAGS=$(curl -s -H "Authorization: JWT $DOCKERHUB_TOKEN" \
              "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" | \
              jq -r '.results | sort_by(.last_updated) | .[].name')

            # Get the list of tags to delete (all except the last 5)
            TAGS_TO_DELETE=$(echo "$TAGS" | head -n -5)

            # Delete old tags using Docker CLI
            for TAG in $TAGS_TO_DELETE; do
              echo "Deleting tag: $TAG"
              docker rmi $REPO:$TAG || true
            done
